language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential 
      - nasm 
      - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL

script: 
  - ./build.sh
